spring:
  application:
    name: football-video-processor
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/football_video_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": false
        "[generate_statistics]": false
        "[show_sql]": false
        "[use_sql_comments]": false
        "[sql-load-script-source]": false
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8080
  servlet:
    context-path: /api

app:
  auth:
    jwt:
      secret: ${JWT_SECRET:veryLongAndSecureJwtSecretKeyUsedForSigningJwtTokens}
      expiration: 86400000 # 24 giờ
      refresh-expiration: 604800000 # 7 ngày
  video:
    upload:
      location: ${VIDEO_UPLOAD_PATH:uploads/videos}
      max-size: 100MB
    processing:
      url: http://localhost:9090/api/process

# Cloudflare R2 Configuration
cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    endpoint: ${R2_ENDPOINT}
    region: ${R2_REGION:auto}
    bucket-name: ${R2_BUCKET_NAME:football-videos}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    "[com.loopy.footballvideoprocessor]": INFO
    "[com.loopy.footballvideoprocessor.security]": INFO
    "[org.springframework.web]": WARN
    "[org.springframework.security]": WARN
    "[org.hibernate]": ERROR
    "[org.hibernate.SQL]": OFF
    "[org.hibernate.type.descriptor.sql]": OFF
    "[org.hibernate.type]": OFF
    "[org.hibernate.orm.jdbc.bind]": OFF
    "[org.hibernate.engine.transaction.internal.TransactionImpl]": OFF
    "[org.hibernate.stat]": OFF
    "[org.hibernate.event]": OFF
  file:
    name: logs/football-video-processor.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      file-name-pattern: logs/football-video-processor.%d{yyyy-MM-dd}.%i.log

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method

rabbitmq:
  exchange:
    video-processing: video-processing-exchange
  queue:
    video-processing: video-processing-queue
    video-result: video-result-queue
  routing-key:
    video-processing: video-processing
    video-result: video-result
