spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    "[com.loopy.footballvideoprocessor]": INFO
    "[org.springframework.web]": WARN

server:
  port: 80
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat

app:
  auth:
    jwt:
      secret: ${JWT_SECRET}
  video:
    upload:
      location: ${VIDEO_UPLOAD_PATH}
    processing:
      url: ${VIDEO_PROCESSING_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
